import type { editor } from "monaco-editor";

/** NovaStudio dark — deep ink canvas, cooler violet accents. */
export const POLARIS_DARK_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "E8E4F5" },
    { token: "comment", foreground: "6B6280", fontStyle: "italic" },
    { token: "string", foreground: "FBBF24" },
    { token: "string.escape", foreground: "F472B6" },
    { token: "number", foreground: "F472B6" },
    { token: "regexp", foreground: "9B8FEF" },
    { token: "keyword", foreground: "A277FF" },
    { token: "keyword.control", foreground: "A277FF" },
    { token: "operator", foreground: "C8C0DC" },
    { token: "delimiter", foreground: "C8C0DC" },
    { token: "type", foreground: "DDD6FE" },
    { token: "type.identifier", foreground: "DDD6FE" },
    { token: "class", foreground: "A5B4FC" },
    { token: "interface", foreground: "A5B4FC" },
    { token: "enum", foreground: "A5B4FC" },
    { token: "typeParameter", foreground: "DDD6FE" },
    { token: "namespace", foreground: "A5B4FC" },
    { token: "function", foreground: "7DD3FC" },
    { token: "method", foreground: "7DD3FC" },
    { token: "variable", foreground: "E8E4F5" },
    { token: "variable.predefined", foreground: "E879F9" },
    { token: "variable.parameter", foreground: "E8E4F5" },
    { token: "property", foreground: "E879F9" },
    { token: "tag", foreground: "A277FF" },
    { token: "metatag", foreground: "A277FF" },
    { token: "attribute.name", foreground: "E8E4F5" },
    { token: "attribute.value", foreground: "FBBF24" },
    { token: "attribute.value.html", foreground: "FBBF24" },
    { token: "attribute.name.html", foreground: "E8E4F5" },
    { token: "tag.html", foreground: "A277FF" },
    { token: "delimiter.html", foreground: "6B6280" },
    { token: "metatag.content.html", foreground: "A277FF" },
    // CSS
    { token: "tag.css", foreground: "A277FF" },
    { token: "attribute.name.css", foreground: "E879F9" },
    { token: "attribute.value.css", foreground: "FBBF24" },
    { token: "attribute.value.number.css", foreground: "F472B6" },
    { token: "attribute.value.unit.css", foreground: "F472B6" },
    { token: "attribute.value.hex.css", foreground: "F472B6" },
    { token: "keyword.css", foreground: "A277FF" },
    { token: "constant", foreground: "E879F9" },
    { token: "annotation", foreground: "FBBF24" },
    { token: "invalid", foreground: "F75464" },
  ],
  colors: {
    "editor.background": "#0E0D14",
    "editor.foreground": "#E8E4F5",
    "editorLineNumber.foreground": "#3F3658",
    "editorLineNumber.activeForeground": "#9B87F5",
    "editorCursor.foreground": "#9B87F5",
    "editor.selectionBackground": "#4C1D9588",
    "editor.inactiveSelectionBackground": "#4C1D9555",
    "editor.selectionHighlightBackground": "#4C1D9544",
    "editor.wordHighlightBackground": "#1C172A80",
    "editor.wordHighlightStrongBackground": "#261E3AA0",
    "editor.findMatchBackground": "#6D28D9AA",
    "editor.findMatchHighlightBackground": "#4C1D9588",
    "editor.findRangeHighlightBackground": "#4C1D9566",
    "editor.hoverHighlightBackground": "#1C172A66",
    "editor.lineHighlightBackground": "#16131F",
    "editor.lineHighlightBorder": "#00000000",
    "editorIndentGuide.background": "#1C172A",
    "editorIndentGuide.activeBackground": "#3F3658",
    "editorWhitespace.foreground": "#1C172A",
    "editorBracketMatch.background": "#4C1D9580",
    "editorBracketMatch.border": "#9B87F5",
    "editorGutter.background": "#0E0D14",
    "editorWidget.background": "#121018",
    "editorWidget.border": "#2C2640",
    "editorWidget.foreground": "#F3F0FF",
    "editorSuggestWidget.background": "#121018",
    "editorSuggestWidget.border": "#2C2640",
    "editorSuggestWidget.foreground": "#F3F0FF",
    "editorSuggestWidget.selectedBackground": "#4C1D95",
    "editorSuggestWidget.selectedForeground": "#FFFFFF",
    "editorSuggestWidget.selectedIconForeground": "#FFFFFF",
    "editorSuggestWidget.highlightForeground": "#9B87F5",
    "editorSuggestWidget.focusHighlightForeground": "#C4B5FD",
    "editorHoverWidget.background": "#121018",
    "editorHoverWidget.border": "#2C2640",
    "editorHoverWidget.foreground": "#F3F0FF",
    "editorError.foreground": "#F75464",
    "editorWarning.foreground": "#FBBF24",
    "editorInfo.foreground": "#9B87F5",
    "editorOverviewRuler.border": "#00000000",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#3F365866",
    "scrollbarSlider.hoverBackground": "#6B628088",
    "scrollbarSlider.activeBackground": "#9B87F5AA",
    "minimap.background": "#0E0D14",
    "minimapSlider.background": "#3F365844",
    "minimapSlider.hoverBackground": "#6B628066",
    "minimapSlider.activeBackground": "#9B87F588",
    "focusBorder": "#9B87F500",
    "input.background": "#0C0B10",
    "input.border": "#2C2640",
    "input.foreground": "#F3F0FF",
    "inputOption.activeBorder": "#9B87F5",
    "inputValidation.errorBackground": "#3A2323",
    "inputValidation.errorBorder": "#F75464",
    "dropdown.background": "#121018",
    "dropdown.border": "#2C2640",
    "dropdown.foreground": "#F3F0FF",
    "list.activeSelectionBackground": "#4C1D95",
    "list.activeSelectionForeground": "#FFFFFF",
    "list.hoverBackground": "#1C172A",
    "list.hoverForeground": "#F3F0FF",
    "list.focusBackground": "#4C1D95",
    "list.focusForeground": "#FFFFFF",
    "list.highlightForeground": "#9B87F5",
    "peekView.border": "#9B87F5",
    "peekViewEditor.background": "#0E0D14",
    "peekViewResult.background": "#121018",
    "peekViewTitle.background": "#121018",
  },
};

/** NovaStudio light — white canvas, purple accents. */
export const POLARIS_LIGHT_THEME: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "", foreground: "1A1228" },
    { token: "comment", foreground: "8B839E", fontStyle: "italic" },
    { token: "string", foreground: "B45309" },
    { token: "string.escape", foreground: "BE185D" },
    { token: "number", foreground: "BE185D" },
    { token: "regexp", foreground: "6D28D9" },
    { token: "keyword", foreground: "6D28D9" },
    { token: "keyword.control", foreground: "6D28D9" },
    { token: "operator", foreground: "1A1228" },
    { token: "delimiter", foreground: "1A1228" },
    { token: "type", foreground: "5B21B6" },
    { token: "type.identifier", foreground: "5B21B6" },
    { token: "class", foreground: "4338CA" },
    { token: "interface", foreground: "4338CA" },
    { token: "function", foreground: "2563EB" },
    { token: "method", foreground: "2563EB" },
    { token: "variable", foreground: "1A1228" },
    { token: "variable.predefined", foreground: "A21CAF" },
    { token: "property", foreground: "A21CAF" },
    { token: "tag", foreground: "6D28D9" },
    { token: "metatag", foreground: "6D28D9" },
    { token: "attribute.name", foreground: "7C3AED" },
    { token: "attribute.value", foreground: "B45309" },
    { token: "attribute.value.html", foreground: "B45309" },
    { token: "attribute.name.html", foreground: "7C3AED" },
    { token: "tag.html", foreground: "6D28D9" },
    { token: "delimiter.html", foreground: "6B6280" },
    // CSS
    { token: "tag.css", foreground: "6D28D9" },
    { token: "attribute.name.css", foreground: "A21CAF" },
    { token: "attribute.value.css", foreground: "B45309" },
    { token: "attribute.value.number.css", foreground: "BE185D" },
    { token: "attribute.value.unit.css", foreground: "BE185D" },
    { token: "attribute.value.hex.css", foreground: "BE185D" },
    { token: "keyword.css", foreground: "6D28D9" },
    { token: "constant", foreground: "A21CAF" },
    { token: "annotation", foreground: "B45309" },
    { token: "invalid", foreground: "DC2626" },
  ],
  colors: {
    "editor.background": "#FFFFFF",
    "editor.foreground": "#1A1228",
    "editorLineNumber.foreground": "#C4B5FD",
    "editorLineNumber.activeForeground": "#6D28D9",
    "editorCursor.foreground": "#6D28D9",
    "editor.selectionBackground": "#E9D5FF",
    "editor.inactiveSelectionBackground": "#E9D5FF88",
    "editor.selectionHighlightBackground": "#E9D5FF55",
    "editor.wordHighlightBackground": "#EFEAF880",
    "editor.wordHighlightStrongBackground": "#E4DCF3A0",
    "editor.findMatchBackground": "#DDD6FE",
    "editor.findMatchHighlightBackground": "#E9D5FF99",
    "editor.findRangeHighlightBackground": "#E9D5FF55",
    "editor.lineHighlightBackground": "#F4F1FA",
    "editor.lineHighlightBorder": "#00000000",
    "editorIndentGuide.background": "#E8E2F2",
    "editorIndentGuide.activeBackground": "#C4B5FD",
    "editorWhitespace.foreground": "#E8E2F2",
    "editorBracketMatch.background": "#E9D5FF80",
    "editorBracketMatch.border": "#A78BFA",
    "editorGutter.background": "#FFFFFF",
    "editorWidget.background": "#FAF8FD",
    "editorWidget.border": "#DDD6EB",
    "editorWidget.foreground": "#1A1228",
    "editorSuggestWidget.background": "#FFFFFF",
    "editorSuggestWidget.border": "#DDD6EB",
    "editorSuggestWidget.foreground": "#1A1228",
    "editorSuggestWidget.selectedBackground": "#EDE9FE",
    "editorSuggestWidget.selectedForeground": "#1A1228",
    "editorSuggestWidget.selectedIconForeground": "#1A1228",
    "editorSuggestWidget.highlightForeground": "#6D28D9",
    "editorSuggestWidget.focusHighlightForeground": "#5B21B6",
    "editorHoverWidget.background": "#FFFFFF",
    "editorHoverWidget.border": "#DDD6EB",
    "editorHoverWidget.foreground": "#1A1228",
    "editorError.foreground": "#DC2626",
    "editorWarning.foreground": "#B45309",
    "editorInfo.foreground": "#6D28D9",
    "editorOverviewRuler.border": "#00000000",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#C4B5FD66",
    "scrollbarSlider.hoverBackground": "#A78BFA88",
    "scrollbarSlider.activeBackground": "#6D28D9AA",
    "minimap.background": "#FFFFFF",
    "focusBorder": "#6D28D900",
    "input.background": "#FFFFFF",
    "input.border": "#DDD6EB",
    "input.foreground": "#1A1228",
    "dropdown.background": "#FFFFFF",
    "dropdown.border": "#DDD6EB",
    "dropdown.foreground": "#1A1228",
    "list.activeSelectionBackground": "#EDE9FE",
    "list.activeSelectionForeground": "#1A1228",
    "list.hoverBackground": "#EFEAF8",
    "list.hoverForeground": "#1A1228",
    "list.focusBackground": "#EDE9FE",
    "list.focusForeground": "#1A1228",
    "list.highlightForeground": "#6D28D9",
  },
};

export const POLARIS_THEME_DARK = "polaris-dark";
export const POLARIS_THEME_LIGHT = "polaris-light";

export function registerNovaStudioThemes(monaco: typeof import("monaco-editor")) {
  monaco.editor.defineTheme(POLARIS_THEME_DARK, POLARIS_DARK_THEME);
  monaco.editor.defineTheme(POLARIS_THEME_LIGHT, POLARIS_LIGHT_THEME);
}
