import type { WorkspaceProject } from "@/features/projects/lib/projects-workspace-types";

const members = [
  { name: "Alex Kim", initials: "AK", color: "#7c3aed" },
  { name: "Sam Rivera", initials: "SR", color: "#2563eb" },
  { name: "Jordan Lee", initials: "JL", color: "#db2777" },
  { name: "Casey Wu", initials: "CW", color: "#ea580c" },
];

export const WORKSPACE_PROJECTS: WorkspaceProject[] = [
  {
    id: "p1",
    name: "AI Chat Platform",
    description: "Multi-model chat workspace with streaming tools and memory.",
    cover: "from-violet-600 via-indigo-500 to-fuchsia-500",
    coverTone: "bg-gradient-to-br from-violet-600 via-indigo-500 to-fuchsia-500",
    tech: ["Next.js", "TypeScript", "AI"],
    status: "in-progress",
    visibility: "shared",
    pinned: true,
    progress: 75,
    lastUpdated: "Updated 2h ago",
    lastOpened: "Opened 25m ago",
    lastEditedBy: "Alex Kim",
    members: members.slice(0, 3),
    owner: members[0],
    stars: 1284,
    forks: 312,
    views: 18420,
    downloads: 890,
    tags: ["AI", "SaaS"],
    trending: true,
    weeklyStars: 186,
  },
  {
    id: "p2",
    name: "Design System Kit",
    description: "Token-driven component library for product teams.",
    cover: "from-sky-500 via-blue-500 to-indigo-600",
    coverTone: "bg-gradient-to-br from-sky-500 via-blue-500 to-indigo-600",
    tech: ["React", "Storybook", "Tailwind"],
    status: "review",
    visibility: "shared",
    pinned: true,
    progress: 62,
    lastUpdated: "Updated 5h ago",
    lastOpened: "Opened 1h ago",
    lastEditedBy: "Sam Rivera",
    members: members.slice(1, 4),
    owner: members[1],
    stars: 842,
    forks: 120,
    views: 9200,
    downloads: 410,
    tags: ["Design", "UI"],
    weeklyStars: 94,
  },
  {
    id: "p3",
    name: "Realtime Collab Board",
    description: "CRDT canvas with presence, cursors, and comments.",
    cover: "from-emerald-500 via-teal-500 to-cyan-600",
    coverTone: "bg-gradient-to-br from-emerald-500 via-teal-500 to-cyan-600",
    tech: ["Vite", "Yjs", "WebGL"],
    status: "in-progress",
    visibility: "private",
    pinned: true,
    progress: 48,
    lastUpdated: "Updated yesterday",
    lastOpened: "Opened 3h ago",
    lastEditedBy: "Jordan Lee",
    members: members.slice(0, 2),
    owner: members[2],
    stars: 560,
    forks: 88,
    views: 6400,
    tags: ["Collab"],
    weeklyStars: 72,
  },
  {
    id: "p4",
    name: "API Gateway Console",
    description: "Observability dashboard for edge routes and quotas.",
    cover: "from-orange-500 via-rose-500 to-purple-600",
    coverTone: "bg-gradient-to-br from-orange-500 via-rose-500 to-purple-600",
    tech: ["Node", "Postgres", "Grafana"],
    status: "shipped",
    visibility: "public",
    pinned: true,
    progress: 100,
    lastUpdated: "Updated 3d ago",
    lastOpened: "Opened 2d ago",
    lastEditedBy: "Casey Wu",
    members: members.slice(2, 4),
    owner: members[3],
    stars: 2104,
    forks: 450,
    views: 30100,
    downloads: 1200,
    tags: ["Infra", "Ops"],
    trending: true,
    weeklyStars: 240,
  },
  {
    id: "p5",
    name: "Task Management App",
    description: "Linear-inspired tracker with AI triage suggestions.",
    cover: "from-fuchsia-500 via-purple-500 to-indigo-600",
    coverTone: "bg-gradient-to-br from-fuchsia-500 via-purple-500 to-indigo-600",
    tech: ["Next.js", "Convex", "Clerk"],
    status: "in-progress",
    visibility: "private",
    pinned: false,
    progress: 40,
    lastUpdated: "Updated 40m ago",
    lastOpened: "Opened 10m ago",
    lastEditedBy: "Alex Kim",
    members: members.slice(0, 3),
    owner: members[0],
    tags: ["Productivity"],
  },
  {
    id: "p6",
    name: "Docs Portal",
    description: "Beautiful product docs with search and versioning.",
    cover: "from-blue-400 via-indigo-500 to-violet-600",
    coverTone: "bg-gradient-to-br from-blue-400 via-indigo-500 to-violet-600",
    tech: ["MDX", "Astro", "Algolia"],
    status: "review",
    visibility: "public",
    pinned: false,
    progress: 70,
    lastUpdated: "Updated 6h ago",
    lastOpened: "Opened 4h ago",
    lastEditedBy: "Sam Rivera",
    members: members.slice(1, 3),
    owner: members[1],
    stars: 390,
    forks: 54,
    views: 5100,
    tags: ["Docs"],
  },
  {
    id: "p7",
    name: "AI Image Generator",
    description: "Community gallery for prompt-driven visual experiments.",
    cover: "from-amber-400 via-orange-500 to-rose-500",
    coverTone: "bg-gradient-to-br from-amber-400 via-orange-500 to-rose-500",
    tech: ["Python", "FastAPI", "React"],
    status: "shipped",
    visibility: "public",
    pinned: false,
    progress: 100,
    lastUpdated: "Updated 1d ago",
    lastOpened: "Opened 1d ago",
    lastEditedBy: "Jordan Lee",
    members,
    owner: members[2],
    stars: 4520,
    forks: 980,
    views: 89000,
    downloads: 3400,
    tags: ["AI", "Community", "Trending"],
    trending: true,
    weeklyStars: 520,
  },
  {
    id: "p8",
    name: "Analytics Studio",
    description: "Interactive charts and cohort analysis for product teams.",
    cover: "from-cyan-400 via-sky-500 to-blue-700",
    coverTone: "bg-gradient-to-br from-cyan-400 via-sky-500 to-blue-700",
    tech: ["TypeScript", "D3", "DuckDB"],
    status: "in-progress",
    visibility: "public",
    pinned: false,
    progress: 55,
    lastUpdated: "Updated 8h ago",
    lastOpened: "Opened 5h ago",
    lastEditedBy: "Casey Wu",
    members: members.slice(0, 2),
    owner: members[3],
    stars: 1670,
    forks: 210,
    views: 22000,
    tags: ["Data", "Charts"],
    trending: true,
    weeklyStars: 160,
  },
];
