import type { editor } from "monaco-editor";

export const GITHUB_DARK_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "e6edf3" },
    { token: "comment", foreground: "8b949e", fontStyle: "italic" },
    { token: "string", foreground: "a5d6ff" },
    { token: "number", foreground: "79c0ff" },
    { token: "keyword", foreground: "ff7b72" },
    { token: "type", foreground: "ffa657" },
    { token: "class", foreground: "ffa657" },
    { token: "function", foreground: "d2a8ff" },
    { token: "variable", foreground: "e6edf3" },
    { token: "variable.predefined", foreground: "79c0ff" },
    { token: "tag", foreground: "7ee787" },
    { token: "attribute.name", foreground: "79c0ff" },
    { token: "attribute.value", foreground: "a5d6ff" },
    { token: "delimiter", foreground: "e6edf3" },
  ],
  colors: {
    "editor.background": "#0d1117",
    "editor.foreground": "#e6edf3",
    "editorLineNumber.foreground": "#6e7681",
    "editorLineNumber.activeForeground": "#e6edf3",
    "editorCursor.foreground": "#2f81f7",
    "editor.selectionBackground": "#264f7844",
    "editor.inactiveSelectionBackground": "#264f7822",
    "editor.lineHighlightBackground": "#161b22",
    "editorIndentGuide.background1": "#21262d",
    "editorIndentGuide.activeBackground1": "#30363d",
    "editorWidget.background": "#161b22",
    "editorWidget.border": "#30363d",
    "editorSuggestWidget.background": "#161b22",
    "editorSuggestWidget.border": "#30363d",
    "editorSuggestWidget.selectedBackground": "#1f6feb44",
    "scrollbarSlider.background": "#6e768166",
    "scrollbarSlider.hoverBackground": "#6e768199",
    "minimap.background": "#0d1117",
  },
};

export const DRACULA_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "f8f8f2" },
    { token: "comment", foreground: "6272a4", fontStyle: "italic" },
    { token: "string", foreground: "f1fa8c" },
    { token: "number", foreground: "bd93f9" },
    { token: "keyword", foreground: "ff79c6" },
    { token: "type", foreground: "8be9fd", fontStyle: "italic" },
    { token: "class", foreground: "8be9fd" },
    { token: "function", foreground: "50fa7b" },
    { token: "variable", foreground: "f8f8f2" },
    { token: "variable.predefined", foreground: "bd93f9" },
    { token: "tag", foreground: "ff79c6" },
    { token: "attribute.name", foreground: "50fa7b" },
    { token: "attribute.value", foreground: "f1fa8c" },
    { token: "delimiter", foreground: "f8f8f2" },
  ],
  colors: {
    "editor.background": "#282a36",
    "editor.foreground": "#f8f8f2",
    "editorLineNumber.foreground": "#6272a4",
    "editorLineNumber.activeForeground": "#f8f8f2",
    "editorCursor.foreground": "#f8f8f0",
    "editor.selectionBackground": "#44475a",
    "editor.inactiveSelectionBackground": "#44475a88",
    "editor.lineHighlightBackground": "#44475a55",
    "editorIndentGuide.background1": "#44475a",
    "editorIndentGuide.activeBackground1": "#6272a4",
    "editorWidget.background": "#21222c",
    "editorWidget.border": "#44475a",
    "editorSuggestWidget.background": "#21222c",
    "editorSuggestWidget.border": "#44475a",
    "editorSuggestWidget.selectedBackground": "#44475a",
    "scrollbarSlider.background": "#44475a66",
    "scrollbarSlider.hoverBackground": "#6272a499",
    "minimap.background": "#282a36",
  },
};

export const NORD_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "d8dee9" },
    { token: "comment", foreground: "616e88", fontStyle: "italic" },
    { token: "string", foreground: "a3be8c" },
    { token: "number", foreground: "b48ead" },
    { token: "keyword", foreground: "81a1c1" },
    { token: "type", foreground: "8fbcbb" },
    { token: "class", foreground: "8fbcbb" },
    { token: "function", foreground: "88c0d0" },
    { token: "variable", foreground: "d8dee9" },
    { token: "variable.predefined", foreground: "d08770" },
    { token: "tag", foreground: "81a1c1" },
    { token: "attribute.name", foreground: "8fbcbb" },
    { token: "attribute.value", foreground: "a3be8c" },
    { token: "delimiter", foreground: "eceff4" },
  ],
  colors: {
    "editor.background": "#2e3440",
    "editor.foreground": "#d8dee9",
    "editorLineNumber.foreground": "#4c566a",
    "editorLineNumber.activeForeground": "#d8dee9",
    "editorCursor.foreground": "#d8dee9",
    "editor.selectionBackground": "#434c5e99",
    "editor.inactiveSelectionBackground": "#434c5e55",
    "editor.lineHighlightBackground": "#3b4252",
    "editorIndentGuide.background1": "#434c5e",
    "editorIndentGuide.activeBackground1": "#4c566a",
    "editorWidget.background": "#3b4252",
    "editorWidget.border": "#434c5e",
    "editorSuggestWidget.background": "#3b4252",
    "editorSuggestWidget.border": "#434c5e",
    "editorSuggestWidget.selectedBackground": "#434c5e",
    "scrollbarSlider.background": "#4c566a66",
    "scrollbarSlider.hoverBackground": "#4c566a99",
    "minimap.background": "#2e3440",
  },
};

export const SOLARIZED_LIGHT_THEME: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "", foreground: "657b83" },
    { token: "comment", foreground: "93a1a1", fontStyle: "italic" },
    { token: "string", foreground: "2aa198" },
    { token: "number", foreground: "d33682" },
    { token: "keyword", foreground: "859900" },
    { token: "type", foreground: "b58900" },
    { token: "class", foreground: "b58900" },
    { token: "function", foreground: "268bd2" },
    { token: "variable", foreground: "657b83" },
    { token: "variable.predefined", foreground: "cb4b16" },
    { token: "tag", foreground: "268bd2" },
    { token: "attribute.name", foreground: "93a1a1" },
    { token: "attribute.value", foreground: "2aa198" },
    { token: "delimiter", foreground: "586e75" },
  ],
  colors: {
    "editor.background": "#fdf6e3",
    "editor.foreground": "#657b83",
    "editorLineNumber.foreground": "#93a1a1",
    "editorLineNumber.activeForeground": "#586e75",
    "editorCursor.foreground": "#657b83",
    "editor.selectionBackground": "#eee8d5",
    "editor.inactiveSelectionBackground": "#eee8d588",
    "editor.lineHighlightBackground": "#eee8d555",
    "editorIndentGuide.background1": "#eee8d5",
    "editorIndentGuide.activeBackground1": "#93a1a1",
    "editorWidget.background": "#eee8d5",
    "editorWidget.border": "#93a1a1",
    "editorSuggestWidget.background": "#eee8d5",
    "editorSuggestWidget.border": "#93a1a1",
    "editorSuggestWidget.selectedBackground": "#ddd6c1",
    "scrollbarSlider.background": "#93a1a166",
    "scrollbarSlider.hoverBackground": "#93a1a199",
    "minimap.background": "#fdf6e3",
  },
};
